# --- Prefix Key ---
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# --- Terminal Settings ---
set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"

# Extended Keys aktivieren (für H, J, K scheint das ja zu reichen)
set -s extended-keys always
set -as terminal-features ',alacritty:RGB'
set -as terminal-features ',alacritty:extkeys'
set-window-option -g xterm-keys on

# --- DER FIX FÜR L (Bypass) ---
# Das hier umgeht die Tmux-Logik nur für Strg+Shift+L
set -s user-keys[0] "\e[108;6u"
bind -n User0 send-keys "\e[108;6u"

# --- Basis Settings ---
set -g mouse on
set-option -g default-shell /usr/bin/fish
set -g base-index 1
setw -g pane-base-index 1
set -s escape-time 0

# --- Optik ---
set -g status-style bg=default,fg=white

# --- Splits ---
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# --- Navigation ---
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# --- Reload ---
bind r source-file ~/.config/tmux/tmux.conf \; display "Config neu geladen!"

# --- Vi-Mode ---
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
