#!/usr/bin/env bash
#
#  _____
# |~>   |     _
# |_____|   ('v') 
# /:::::\  /{w w}\ 
#
# created by: Florian Orzol
# my deactivated autostart settings for herbstluftwm


#    <')
# \_;( )

# ===========
# >> THEME <<
# ===========

hc set frame_border_active_color '#11A1DD' # active and focused frame color blue 
hc set frame_border_normal_color '#064058' # inactive frame color dark blue
hc set frame_bg_normal_color '#565656aa' # inactive frame color grey
hc set frame_bg_active_color '#345F0Caa' # active frame color green
hc set show_frame_decorations 'focused_if_multiple' # show frame decorations only if more than one client is open

# --------------------------------
# >> window settings <<

# border colors
hc set window_border_active_color '#11A1DD' # active window border color
# window gaps
hc set window_gap 1 # window gap
hc set window_border_width 3 # window border width
hc set window_border_inner_width 3 # window border inner width


hc attr theme.title_font '-*-fixed-medium-r-*-13*-13-*-*-*-*-*-*-*' # title font size
hc attr theme.normal.color '#323232' # normal color of the title
hc attr theme.active.tab_outer_color 'white' # color of the outer border of the active window
hc attr theme.inner_color black # color of the inner border of the active window
hc attr theme.floating.outer_color black # color of the outer border of the floating window
hc attr theme.active.inner_color '#11A1DD' # color of the inner border of the active window
hc attr theme.urgent.inner_color '#9A65B0' # color of the inner border of the urgent window
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 0 # outer border width for tiling windows
hc attr theme.background_color '#141414' # background color of the frame

hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on