#!/bin/bash

# Speichern Sie die ID des aktuellen Monitors
monitor=$(herbstclient list_monitors | grep '\[FOCUS\]' | cut -d: -f1)

# Führen Sie dmenu_run aus
prog=$(dmenu_path | dmenu "$@")



# Starten Sie das Programm auf dem gespeicherten Monitor

