# This file was created by fish when upgrading to version 4.3.
# Its purpose is to facilitate the migration of theme variables from universal to global scope.
#
# IMPORTANT: Do not edit this file manually.
# It is managed and will be overwritten by the `fish_config` web-configuration tool.
#
# To customize your Fish shell theme, you should:
# 1. Delete this file.
# 2. Add appropriate `set --global fish_color_*` commands to your `~/.config/fish/config.fish` file.
#
# For more information on syntax highlighting and theme customization, refer to:
# - `help interactive#syntax-highlighting`
# - `man fish-interactive | less +/^SYNTAX.HIGHLIGHTING`
# - Fish 4.3.0 release notes (`help relnotes`).

# Global theme color variables, set by fish_config.
set --global fish_color_autosuggestion brblack
set --global fish_color_cancel -r
set --global fish_color_command blue
set --global fish_color_comment red
set --global fish_color_cwd green
set --global fish_color_cwd_root red
set --global fish_color_end green
set --global fish_color_error brred
set --global fish_color_escape brcyan
set --global fish_color_history_current --bold
set --global fish_color_host normal
set --global fish_color_host_remote yellow
set --global fish_color_normal normal
set --global fish_color_operator brcyan
set --global fish_color_param cyan
set --global fish_color_quote yellow
set --global fish_color_redirection cyan --bold
set --global fish_color_search_match white --background=brblack
set --global fish_color_selection white --bold --background=brblack
set --global fish_color_status red
set --global fish_color_user brgreen
set --global fish_color_valid_path --underline
set --global fish_pager_color_completion normal
set --global fish_pager_color_description yellow -i
set --global fish_pager_color_prefix normal --bold --underline
set --global fish_pager_color_progress brwhite --background=cyan
set --global fish_pager_color_selected_background -r
