#!/bin/bash
#
#  
#   _____        _
#  |~>   |     ('v') 
#  /:::::\    /{w w}\ 
# --------------------------------
# Copyright Florian Orzol
#
# description:
# date: 2025-06-06
# version:  0.0.1
#
#    <')
# \_;( )
# >>>> START SCRIPT <<<< #
#

#-tags Install and setup my arch linux desktop environment


function install-nvim {

	_Section "Install Neovim"
	_cmd "sudo pacman -S neovim"

	_Section "Requirements"
	_cmd sudo pacman -S nodejs npm

	_Section "Install Plugins"
	_Info "clone configs and plugins"
	_Info "Execute :Lazy and sync in Neovim"

	_Section "Authorize Copilot"
	_Info "Exectute :Copilot auth in Neovim"

	_Section "Enable Copilot"
	_Info "Execute :Copilot enable in Neovim"
}







